In [1]:
import numpy as np 
import pandas as pd 

In [2]:
data = pd.read_csv("training_v2.csv")

In [3]:
df = data[['hospital_death', 'age', 'bmi', 'gender', 'ethnicity', 'glucose_apache', 'heart_rate_apache', 'diabetes_mellitus', 'apache_2_bodysystem']]
df.head()

hospital_death   age    bmi gender  ethnicity  glucose_apache  \
0               0  68.0  22.73      M  Caucasian           168.0   
1               0  77.0  27.42      F  Caucasian           145.0   
2               0  25.0  31.95      F  Caucasian             NaN   
3               0  81.0  22.64      F  Caucasian           185.0   
4               0  19.0    NaN      M  Caucasian             NaN   

   heart_rate_apache  diabetes_mellitus apache_2_bodysystem  
0              118.0                1.0      Cardiovascular  
1              120.0                1.0         Respiratory  
2              102.0                0.0           Metabolic  
3              114.0                0.0      Cardiovascular  
4               60.0                0.0              Trauma

In [4]:
len(df)

91713

In [5]:
df = df.dropna()

In [6]:
len(df)

73200

In [7]:
df_1 = df.copy()
df_1

hospital_death   age        bmi gender         ethnicity  \
0                   0  68.0  22.730000      M         Caucasian   
1                   0  77.0  27.420000      F         Caucasian   
3                   0  81.0  22.640000      F         Caucasian   
5                   0  67.0  27.560000      M         Caucasian   
6                   0  59.0  57.450000      F         Caucasian   
11                  0  80.0  27.382812      F         Caucasian   
14                  0  81.0  38.189067      M         Caucasian   
16                  0  30.0  23.383178      M         Caucasian   
17                  0  46.0  25.845717      M          Hispanic   
18                  0  65.0  28.408929      M          Hispanic   
20                  0  79.0  28.376100      F         Caucasian   
21                  0  80.0  35.659989      M         Caucasian   
23                  0  87.0  21.963763      M         Caucasian   
24                  0  60.0  29.509959      M         Caucasian   
25                  1  68.0  26.010703      F         Caucasian   
26                  0  85.0  23.809770      F         Caucasian   
27                  0  79.0  23.408979      F         Caucasian   
29                  0  60.0  26.485715      M  African American   
31                  0  68.0  27.560503      M         Caucasian   
32                  0  30.0  17.003550      F         Caucasian   
33                  0  45.0  32.129842      M         Caucasian   
34                  0  53.0  23.626083      F         Caucasian   
35                  0  71.0  38.497016      M         Caucasian   
38                  0  85.0  21.889645      F         Caucasian   
39                  0  65.0  26.286417      M  African American   
40                  0  82.0  23.738117      M         Caucasian   
42                  0  87.0  18.745276      F         Caucasian   
43                  0  52.0  23.039099      F         Caucasian   
45                  0  75.0  33.480398      M         Caucasian   
46                  1  64.0  16.980389      M         Caucasian   
...               ...   ...        ...    ...               ...   
91675               0  28.0  67.814990      F  African American   
91676               0  74.0  26.153278      F         Caucasian   
91677               0  32.0  32.304688      F         Caucasian   
91678               0  37.0  46.155648      M         Caucasian   
91679               0  69.0  27.172742      M  African American   
91680               0  47.0  25.581066      M         Caucasian   
91681               0  70.0  32.522449      M          Hispanic   
91682               0  83.0  30.080782      M         Caucasian   
91683               0  75.0  41.240169      F         Caucasian   
91684               0  19.0  21.849332      F             Asian   
91686               0  86.0  31.157451      F         Caucasian   
91687               0  71.0  32.690378      M         Caucasian   
91688               0  49.0  31.866165      M         Caucasian   
91690               0  83.0  26.760649      F         Caucasian   
91692               0  36.0  20.575852      F         Caucasian   
91694               0  58.0  33.211359      M         Caucasian   
91695               0  49.0  21.748106      F         Caucasian   
91698               0  47.0  51.439842      M         Caucasian   
91699               0  57.0  33.810548      M  African American   
91700               0  85.0  25.091529      M         Caucasian   
91701               0  21.0  24.874059      M         Caucasian   
91702               0  18.0  20.284799      M         Caucasian   
91703               0  53.0  45.935203      M         Caucasian   
91704               0  38.0  32.992923      M         Caucasian   
91705               0  67.0  28.876843      M  African American   
91706               0  54.0  19.770448      M   Native American   
91708               0  75.0  23.060250      M         Caucasian   
91709               0  56.0  47.179671      F         

In [8]:
bins_age = [10, 20, 30, 40, 50, 60, 70, 80, 90]
bins_age
# a_bins = df.a.groupby(cut(df.a,bins))

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [9]:
#Adding labels in 
df_1['age_group'] = pd.cut(df_1.age, bins_age)
df_1.head()

hospital_death   age    bmi gender  ethnicity  glucose_apache  \
0               0  68.0  22.73      M  Caucasian           168.0   
1               0  77.0  27.42      F  Caucasian           145.0   
3               0  81.0  22.64      F  Caucasian           185.0   
5               0  67.0  27.56      M  Caucasian           156.0   
6               0  59.0  57.45      F  Caucasian           197.0   

   heart_rate_apache  diabetes_mellitus apache_2_bodysystem age_group  
0              118.0                1.0      Cardiovascular  (60, 70]  
1              120.0                1.0         Respiratory  (70, 80]  
3              114.0                0.0      Cardiovascular  (80, 90]  
5              113.0                1.0          Neurologic  (60, 70]  
6              133.0                1.0         Respiratory  (50, 60]

In [10]:
bins_bmi = [1, 18.5, 25.0, 30.0, 40.0, 99.9]
bins_bmi

[1, 18.5, 25.0, 30.0, 40.0, 99.9]

In [11]:
#generating the labels for bins
bmi_labels = ('Underweight','Normal', 'Overweight', 'Obesity', 'Extreme Obesity')

In [12]:
df_1['bmi_group'] = pd.cut(df_1.bmi, bins_bmi, right=False, labels =bmi_labels)
df_1.head()

hospital_death   age    bmi gender  ethnicity  glucose_apache  \
0               0  68.0  22.73      M  Caucasian           168.0   
1               0  77.0  27.42      F  Caucasian           145.0   
3               0  81.0  22.64      F  Caucasian           185.0   
5               0  67.0  27.56      M  Caucasian           156.0   
6               0  59.0  57.45      F  Caucasian           197.0   

   heart_rate_apache  diabetes_mellitus apache_2_bodysystem age_group  \
0              118.0                1.0      Cardiovascular  (60, 70]   
1              120.0                1.0         Respiratory  (70, 80]   
3              114.0                0.0      Cardiovascular  (80, 90]   
5              113.0                1.0          Neurologic  (60, 70]   
6              133.0                1.0         Respiratory  (50, 60]   

         bmi_group  
0           Normal  
1       Overweight  
3           Normal  
5       Overweight  
6  Extreme Obesity

In [13]:
bins_glucose = [1, 60, 80, 140, 200, 350,999]
bins_glucose

[1, 60, 80, 140, 200, 350, 999]

In [14]:
#generating the labels for bins
glucose_labels = ('Hypoglycemia','Early hypoglycemia', 'Normal', 'Pre Diabetes', 'Diabetes', 'Extreme Diabetes')

In [15]:
df_1['glucose_group'] = pd.cut(df_1.glucose_apache, bins_glucose, right=False, labels =glucose_labels)
df_1.head()

hospital_death   age    bmi gender  ethnicity  glucose_apache  \
0               0  68.0  22.73      M  Caucasian           168.0   
1               0  77.0  27.42      F  Caucasian           145.0   
3               0  81.0  22.64      F  Caucasian           185.0   
5               0  67.0  27.56      M  Caucasian           156.0   
6               0  59.0  57.45      F  Caucasian           197.0   

   heart_rate_apache  diabetes_mellitus apache_2_bodysystem age_group  \
0              118.0                1.0      Cardiovascular  (60, 70]   
1              120.0                1.0         Respiratory  (70, 80]   
3              114.0                0.0      Cardiovascular  (80, 90]   
5              113.0                1.0          Neurologic  (60, 70]   
6              133.0                1.0         Respiratory  (50, 60]   

         bmi_group glucose_group  
0           Normal  Pre Diabetes  
1       Overweight  Pre Diabetes  
3           Normal  Pre Diabetes  
5       Overweight  Pre Diabetes  
6  Extreme Obesity  Pre Diabetes

In [16]:
df_age = df_1[['apache_2_bodysystem', 'age_group']]
df_age = df_age.replace('Undefined diagnoses', 'Undefined Diagnoses')

In [17]:
# df_age.index = df_age['apache_2_bodysystem']

In [18]:
df_age

apache_2_bodysystem age_group
0          Cardiovascular  (60, 70]
1             Respiratory  (70, 80]
3          Cardiovascular  (80, 90]
5              Neurologic  (60, 70]
6             Respiratory  (50, 60]
11             Neurologic  (70, 80]
14            Respiratory  (80, 90]
16         Cardiovascular  (20, 30]
17            Respiratory  (40, 50]
18             Neurologic  (60, 70]
20             Neurologic  (70, 80]
21         Cardiovascular  (70, 80]
23         Cardiovascular  (80, 90]
24         Cardiovascular  (50, 60]
25         Cardiovascular  (60, 70]
26       Gastrointestinal  (80, 90]
27         Cardiovascular  (70, 80]
29         Cardiovascular  (50, 60]
31            Respiratory  (60, 70]
32              Metabolic  (20, 30]
33       Gastrointestinal  (40, 50]
34         Cardiovascular  (50, 60]
35             Neurologic  (70, 80]
38            Respiratory  (80, 90]
39         Cardiovascular  (60, 70]
40                 Trauma  (80, 90]
42         Cardiovascular  (80, 90]
43             Neurologic  (50, 60]
45         Cardiovascular  (70, 80]
46             Neurologic  (60, 70]
...                   ...       ...
91675         Respiratory  (20, 30]
91676      Cardiovascular  (70, 80]
91677          Neurologic  (30, 40]
91678    Gastrointestinal  (30, 40]
91679      Cardiovascular  (60, 70]
91680              Trauma  (40, 50]
91681      Cardiovascular  (60, 70]
91682      Cardiovascular  (80, 90]
91683      Cardiovascular  (70, 80]
91684           Metabolic  (10, 20]
91686      Cardiovascular  (80, 90]
91687          Neurologic  (70, 80]
91688      Cardiovascular  (40, 50]
91690      Cardiovascular  (80, 90]
91692           Metabolic  (30, 40]
91694      Cardiovascular  (50, 60]
91695          Neurologic  (40, 50]
91698    Gastrointestinal  (40, 50]
91699      Cardiovascular  (50, 60]
91700    Gastrointestinal  (80, 90]
91701           Metabolic  (20, 30]
91702           Metabolic  (10, 20]
91703      Cardiovascular  (50, 60]
91704           Metabolic  (30, 40]
91705           Metabolic  (60, 70]
91706      Cardiovascular  (50, 60]
91708      Cardiovascular  (70, 80]
91709      Cardiovascular  (50, 60]
91710           Metabolic  (40, 50]
91712    Gastrointestinal  (80, 90]

[73200 rows x 2 columns]

In [19]:
df_age = pd.crosstab(df_age['apache_2_bodysystem'], df_age['age_group'], rownames=['diagnosis '], colnames=['age group'])
df_age

age group            (10, 20]  (20, 30]  (30, 40]  (40, 50]  (50, 60]  \
diagnosis                                                               
Cardiovascular            121       716      1164      2659      5700   
Gastrointestinal           27       170       362       694      1369   
Haematologic                7        38        29        48        84   
Metabolic                 357      1031       981      1226      1328   
Neurologic                 95       389       599      1005      1882   
Renal/Genitourinary        13       142       167       177       387   
Respiratory                68       346       436       844      1857   
Trauma                    135       382       291       327       416   
Undefined Diagnoses        16        46        89       288       856   

age group            (60, 70]  (70, 80]  (80, 90]  
diagnosis                                          
Cardiovascular           7947      7895      5152  
Gastrointestinal         1735      1741      1278  
Haematologic              119       118        71  
Metabolic                 787       482       257  
Neurologic               2125      1963      1372  
Renal/Genitourinary       478       404       257  
Respiratory              2298      2255      1294  
Trauma                    451       463       469  
Undefined Diagnoses      1258       906       261

In [20]:
df_bmi = df_1[['age_group', 'bmi_group']]
# df_bmi.index = df_bmi['age_group']
df_bmi = pd.crosstab(df_bmi['age_group'], df_bmi['bmi_group'], rownames=['age group'], colnames=['bmi group'])
df_bmi

bmi group  Underweight  Normal  Overweight  Obesity  Extreme Obesity
age group                                                           
(10, 20]            78     416         180      128               37
(20, 30]           186    1299         808      704              263
(30, 40]           138    1133        1115     1171              561
(40, 50]           222    1725        1962     2318             1041
(50, 60]           526    3346        3810     4391             1806
(60, 70]           584    3972        5037     5660             1945
(70, 80]           609    4419        5322     4736             1141
(80, 90]           578    4013        3439     2065              316

In [21]:
df_glucose = df_1[['bmi_group', 'glucose_group']]
# df_glucose.index = df_glucose['bmi_group']
df_glucose = pd.crosstab(df_glucose['bmi_group'], df_glucose['glucose_group'], rownames=['bmi group'], colnames=['glucose_group'])
df_glucose

glucose_group    Hypoglycemia  Early hypoglycemia  Normal  Pre Diabetes  \
bmi group                                                                 
Underweight                94                 321    1354           579   
Normal                    466                1676    9787          4396   
Overweight                365                1295    9908          5273   
Obesity                   348                1019    8324          5522   
Extreme Obesity           138                 348    2413          1889   

glucose_group    Diabetes  Extreme Diabetes  
bmi group                                    
Underweight           417               156  
Normal               3144               854  
Overweight           3985               847  
Obesity              4876              1084  
Extreme Obesity      1852               470

In [22]:
df_mortality = df_1[['glucose_group', 'hospital_death']]
# df_mortality.index = df_mortality['glucose_group']

df_mortality = pd.crosstab(df_mortality['glucose_group'], df_mortality['hospital_death'], rownames=['glucose_group'], colnames=['mortality'])
df_mortality

mortality               0     1
glucose_group                  
Hypoglycemia         1059   352
Early hypoglycemia   4229   430
Normal              29999  1787
Pre Diabetes        16156  1503
Diabetes            12594  1680
Extreme Diabetes     2936   475

In [23]:
display(df_age.stack().values)
display(df_bmi.stack().values)
display(df_glucose.stack().values)
display(df_mortality.stack().values)

array([ 121,  716, 1164, 2659, 5700, 7947, 7895, 5152,   27,  170,  362,
        694, 1369, 1735, 1741, 1278,    7,   38,   29,   48,   84,  119,
        118,   71,  357, 1031,  981, 1226, 1328,  787,  482,  257,   95,
        389,  599, 1005, 1882, 2125, 1963, 1372,   13,  142,  167,  177,
        387,  478,  404,  257,   68,  346,  436,  844, 1857, 2298, 2255,
       1294,  135,  382,  291,  327,  416,  451,  463,  469,   16,   46,
         89,  288,  856, 1258,  906,  261], dtype=int64)

array([  78,  416,  180,  128,   37,  186, 1299,  808,  704,  263,  138,
       1133, 1115, 1171,  561,  222, 1725, 1962, 2318, 1041,  526, 3346,
       3810, 4391, 1806,  584, 3972, 5037, 5660, 1945,  609, 4419, 5322,
       4736, 1141,  578, 4013, 3439, 2065,  316], dtype=int64)

array([  94,  321, 1354,  579,  417,  156,  466, 1676, 9787, 4396, 3144,
        854,  365, 1295, 9908, 5273, 3985,  847,  348, 1019, 8324, 5522,
       4876, 1084,  138,  348, 2413, 1889, 1852,  470], dtype=int64)

array([ 1059,   352,  4229,   430, 29999,  1787, 16156,  1503, 12594,
        1680,  2936,   475], dtype=int64)

In [24]:
values = np.concatenate((df_age.stack().values, df_bmi.stack().values, df_glucose.stack().values, df_mortality.stack().values))
values

array([  121,   716,  1164,  2659,  5700,  7947,  7895,  5152,    27,
         170,   362,   694,  1369,  1735,  1741,  1278,     7,    38,
          29,    48,    84,   119,   118,    71,   357,  1031,   981,
        1226,  1328,   787,   482,   257,    95,   389,   599,  1005,
        1882,  2125,  1963,  1372,    13,   142,   167,   177,   387,
         478,   404,   257,    68,   346,   436,   844,  1857,  2298,
        2255,  1294,   135,   382,   291,   327,   416,   451,   463,
         469,    16,    46,    89,   288,   856,  1258,   906,   261,
          78,   416,   180,   128,    37,   186,  1299,   808,   704,
         263,   138,  1133,  1115,  1171,   561,   222,  1725,  1962,
        2318,  1041,   526,  3346,  3810,  4391,  1806,   584,  3972,
        5037,  5660,  1945,   609,  4419,  5322,  4736,  1141,   578,
        4013,  3439,  2065,   316,    94,   321,  1354,   579,   417,
         156,   466,  1676,  9787,  4396,  3144,   854,   365,  1295,
        9908,  5273,

In [25]:

'(10, 20]', '(20, 30]','(30, 40]','(40, 50]','(50, 60]', '(60, 70]', '(70, 80]', '(80, 90]'
'Underweight', 'Normal', 'Overweight', 'Obesity', 'Extreme Obesity'
'Hypoglycemia', 'Early hypoglycemia', 'Normal', 'Pre Diabetes','Diabetes', 'Extreme Diabetes'

('Hypoglycemia',
 'Early hypoglycemia',
 'Normal',
 'Pre Diabetes',
 'Diabetes',
 'Extreme Diabetes')

In [27]:
import plotly.graph_objs as go
import plotly.offline as py
data = dict(type='sankey', valueformat = ".2f", valuesuffix = "%", node = dict(pad = 15,\
            thickness = 20, line = dict(color = "black", width = 0.5),
      #label the nodes of the Sankey diagram
      label = ['Cardiovascular','Gastrointestinal','Haematologic','Metabolic','Neurologic','Renal/Genitourinary',\
               'Respiratory','Trauma','Undefined Diagnoses', '(10, 20]', '(20, 30]','(30, 40]','(40, 50]',\
               '(50, 60]', '(60, 70]', '(70, 80]', '(80, 90]', 'Underweight', 'Normal', 'Overweight', \
               'Obesity', 'Extreme Obesity', 'Hypoglycemia', 'Early hypoglycemia', 'Normal', \
               'Pre Diabetes','Diabetes', 'Extreme Diabetes','Live', 'Dead'],
      #assign colors to the nodes
      color = ['darkgreen', 'deepskyblue', 'aqua', 'darksalmon', 'darkmagenta', 'darkorchid', 'darkolivegreen', 'orangered', 'blue',\
               'brown', 'burlywood', 'cadetblue','chartreuse', 'chocolate', 'coral', 'cornflowerblue','cornsilk', \
               'crimson', 'darkkhaki','green','tomato', 'yellow','darkgreen', 'deepskyblue', 'aqua', 'darksalmon', 'darkmagenta',\
               'darkorchid', 'darkolivegreen', 'orangered', 'blue','brown', 'burlywood', 'cadetblue','chartreuse', 'chocolate', \
               'coral', 'cornflowerblue','cornsilk','crimson', 'darkkhaki']),
    #sets the target(Fossil Fuels) to the sources(G20 Countries) and give tragets their value(percentage share)
    link = dict(
      source = [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,6,6,6,6,6,6,\
                6,6,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,9,9,9,9,9,10,10,10,10,10,11,11,11,11,11,12,12,12,12,12,13,13,13,13,\
                13,14,14,14,14,14,15,15,15,15,15,16,16,16,16,16,17,17,17,17,17,17,18,18,18,18,18,18,19,19,19,19,19,19,20,20,20,20,\
                20,20,21,21,21,21,21,21,22,22,23,23,24,24,25,25,26,26,27,27],
      target = [9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,\
                16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,9,10,11,12,13,14,15,16,17,18,19,20,21,\
               17,18,19,20,21,17,18,19,20,21,17,18,19,20,21,17,18,19,20,21,17,18,19,20,21,17,18,19,20,21,17,18,19,20,21,\
               22,23,24,25,26,27,22,23,24,25,26,27,22,23,24,25,26,27,22,23,24,25,26,27,22,23,24,25,26,27,\
                28,29,28,29,28,29,28,29,28,29,28,29],
      value = values))
#sets the layout for the plot
layout =  go.Layout(title = "Effect of Age, BMI and Glucose on Mortality", font = dict(size = 15))
fig = go.Figure(data=[data], layout=layout)
py.iplot(fig, validate=False) #plots the diagram